import Head from 'next/head'
import React, { useState } from 'react'
import { Header } from '../../components/header/Header'
import ReactCountryFlag from 'react-country-flag'
import { VscClose } from 'react-icons/vsc'

interface Props {}

export default function PoolCode(props: Props) {
  const [activeItem, setActiveItem] = useState('your_guesses')

  return (
    <>
      <Head>
        <title>NLW Copa | Pool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen min-h-screen bg-gray-900 ">
        <Header />
        <section className="bg-gray-800 w-[600px] mt-8 mx-auto rounded text-white shadow-xl">
          <div className="w-[600px] mx-auto">
            <button className="bg-ignite-500 hover:brightness-110 w-full text-white font-bold text-sm uppercase px-6 py-4 rounded-t">
              Criar palpite
            </button>
          </div>
          <div>
            <div className="font-bold rounded gap-x-2 flex justify-between min-h-[50px] max-h-[50px] p-2">
              <span
                onClick={() => setActiveItem('your_guesses')}
                className={`${
                  activeItem === 'your_guesses' && 'bg-gray-600'
                } rounded cursor-pointer flex items-center w-full justify-center min-h-full px-4`}
              >
                Seus palpites
              </span>
              <span
                onClick={() => setActiveItem('all_guesses')}
                className={`${
                  activeItem === 'all_guesses' && 'bg-gray-600'
                } rounded cursor-pointer flex items-center w-full justify-center min-h-full px-4`}
              >
                Todos palpites
              </span>
              <span
                onClick={() => setActiveItem('group_ranking')}
                className={`${
                  activeItem === 'group_ranking' && 'bg-gray-600'
                } rounded cursor-pointer flex items-center w-full justify-center min-h-full px-4`}
              >
                Ranking do grupo
              </span>
            </div>
          </div>
        </section>
        {activeItem === 'your_guesses' && (
          <div className="bg-gray-800 border-b-[3px] p-6 border-b-yellow-500 w-[600px] mt-4 mx-auto rounded text-white shadow-xl">
            <div className="text-center flex-col">
              <div>
                <h2 className="font-bold text-2xl">Brasil vs. Argentina</h2>
                <span className="text-gray-200">
                  22 de Novembro de 2022 às 16:00h
                </span>
              </div>
            </div>
            <div className="flex justify-center items-center mt-4">
              <div className="flex gap-x-2 justify-center items-center">
                <span className="flex items-center justify-center h-[35px] w-[50px] rounded bg-gray-900 border border-gray-800 text-white">
                  10
                </span>
                <ReactCountryFlag
                  countryCode="BR"
                  svg
                  style={{
                    width: '2.5em',
                    height: '2.5em',
                  }}
                  title="US"
                />
              </div>
              <VscClose className="text-gray-200 text-3xl mx-5" />
              <div className="flex gap-x-2 justify-center items-center">
                <ReactCountryFlag
                  countryCode="US"
                  svg
                  style={{
                    width: '2.5em',
                    height: '2.5em',
                  }}
                  title="US"
                />
                <span className="flex items-center justify-center h-[35px] w-[50px] rounded bg-gray-900 border border-gray-800 text-white">
                  1
                </span>
              </div>
            </div>
          </div>
        )}
        {activeItem === 'all_guesses' && (
          <div className="bg-gray-800 relative border-b-[3px] p-6 border-b-yellow-500 w-[600px] mt-4 mx-auto rounded text-white shadow-xl">
            <div className="text-center flex-col">
              <div>
                <h2 className="font-bold text-2xl">Brasil vs. Argentina</h2>
                <span className="text-gray-200">
                  22 de Novembro de 2022 às 16:00h
                </span>
              </div>
            </div>
            <div className="flex justify-center items-center mt-4">
              <div className="flex gap-x-2 justify-center items-center">
                <span className="flex items-center justify-center h-[35px] w-[50px] rounded bg-gray-900 border border-gray-800 text-white">
                  10
                </span>
                <ReactCountryFlag
                  countryCode="BR"
                  svg
                  style={{
                    width: '2.5em',
                    height: '2.5em',
                  }}
                  title="US"
                />
              </div>
              <VscClose className="text-gray-200 text-3xl mx-5" />
              <div className="flex gap-x-2 justify-center items-center">
                <ReactCountryFlag
                  countryCode="US"
                  svg
                  style={{
                    width: '2.5em',
                    height: '2.5em',
                  }}
                  title="US"
                />
                <span className="flex items-center justify-center h-[35px] w-[50px] rounded bg-gray-900 border border-gray-800 text-white">
                  1
                </span>
              </div>
            </div>
            <div className="w-full absolute left-0 bottom-1 text-sm text-center">
              <span>Criado por </span>
              <span className="w-fit text-yellow-500 uppercase font-bold mx-auto">
                Gabriel Sena
              </span>
            </div>
          </div>
        )}
        {activeItem === 'group_ranking' && (
          <div className="bg-gray-800 border-b-[3px] p-6 border-b-yellow-500 w-[600px] mt-4 mx-auto rounded text-white shadow-xl">
            <div className="flex items-center justify-between">
              <div className="flex gap-x-2 items-center">
                <img
                  src="https://github.com/stardusteight-d4c.png"
                  className="w-14 h-14 rounded-full"
                />
                <div>
                  <h2 className="text-xl font-bold">
                    Gabriel Sena{' '}
                    <span className="!text-base font-medium text-gray-300">
                      (você)
                    </span>
                  </h2>
                  <span className="text-gray-300">36 ponto(s)</span>
                </div>
              </div>
              <div className="text-center px-4 font-bold bg-yellow-500 rounded-full text-gray-900">
                1º
              </div>
            </div>
          </div>
        )}
      </main>
    </>
  )
}
